import { Question } from './types';

export const ANSWER_OPTIONS = [
  { value: 1, label: 'Không', description: 'Hoàn toàn không xuất hiện' },
  { value: 2, label: 'Hiếm khi', description: '1-3 ngày/tuần hoặc < 1 tuần/tháng' },
  { value: 3, label: 'Thỉnh thoảng', description: '3-4 ngày/tuần hoặc 1-2 tuần/tháng' },
  { value: 4, label: 'Thường xuyên', description: '4-6 ngày/tuần hoặc 2-3 tuần/tháng' },
  { value: 5, label: 'Luôn luôn', description: 'Xuất hiện hầu hết các ngày' },
];

export const CCMQ_QUESTIONS: Question[] = [
  // Page 2
  { id: 1, text: "Bạn có cảm thấy sức khỏe mình tốt không?", subText: "Có nhiều sức lực, sức khỏe để làm việc hoặc tham gia các hoạt động khác." },
  { id: 2, text: "Bạn có cảm thấy dễ bị mệt mỏi không?", subText: "Sau khi làm việc gắng sức hay xuất hiện tình trạng mệt mỏi kéo dài > 1 ngày." },
  { id: 3, text: "Bạn có hay bị hụt hơi (hơi thở ngắn, thở không sâu) khi nói chuyện không?" },
  { id: 4, text: "Bạn có hay hồi hộp hay đánh trống ngực không?", subText: "Có hoặc không có yếu tố kích thích như: lo lắng, sợ hãi, tức giận." },
  { id: 5, text: "Bạn có dễ bị hoa mắt hoặc chóng mặt khi đứng lên không?", subText: "Cảm giác đầu bồng bềnh, nhẹ. Hoặc thấy tối sầm mặt mũi, mất thăng bằng." },
  { id: 6, text: "Bạn có thích sự yên tĩnh và rất lười nói chuyện không?" },
  { id: 7, text: "Bạn có giọng nói nhỏ, yếu và không có sức không?" },
  { id: 8, text: "Bạn có hay quên mọi thứ hay không?" },
  { id: 9, text: "Bạn có thường cảm thấy chán nản và phiền muộn không?" },
  { id: 10, text: "Bạn có dễ bị căng thẳng, bất an không?" },
  { id: 11, text: "Bạn có phải là người nhạy cảm, dễ xúc động, dễ bị tổn thương không?" },
  // Page 3
  { id: 12, text: "Bạn có thường sợ hãi hoặc hoảng sợ không?", subText: "Gặp mọi việc thường dễ sợ hãi, hoặc bình thường vô cớ tự cảm thấy hoang mang sợ sệt." },
  { id: 13, text: "Bạn có bị đau ở hông sườn hoặc căng tức vú không?" },
  { id: 14, text: "Bạn có cảm thấy tức ngực hoặc đầy bụng không?" },
  { id: 15, text: "Bạn có thường thở dài không?" },
  { id: 16, text: "Bạn có cảm thấy cơ thể nặng nề hoặc khó chịu không?" },
  { id: 17, text: "Bạn có cảm thấy lòng bàn tay và lòng bàn chân của mình nóng không?" },
  { id: 18, text: "Tay chân của bạn có lạnh không?" },
  { id: 19, text: "Bạn có thấy dễ bị lạnh ở vùng bụng, lưng, thắt lưng hoặc đầu gối không?" },
  { id: 20, text: "Bạn có thấy sợ lạnh và phải mặc nhiều quần áo hơn những người khác không?" },
  { id: 21, text: "Bạn có cảm thấy cơ thể hoặc là khuôn mặt nóng không?" },
  { id: 22, text: "Bạn không thể chịu được lạnh (khi vào mùa đông, ngồi dưới máy lạnh hay quạt vào mùa hè,…) như người xung quanh không?" },
  { id: 23, text: "Bạn có dễ bị cảm lạnh hơn những người khác không?" },
  { id: 24, text: "Bạn có hắt hơi ngay cả khi không bị cảm lạnh không?" },
  { id: 25, text: "Bạn có bị sổ mũi hay nghẹt mũi ngay cả khi không bị cảm lạnh không?" },
  { id: 26, text: "Bạn có ho hay khò khè khi thay đổi thời tiết, nhiệt độ, hoặc ngửi mùi lạ không?" },
  // Page 4
  { id: 27, text: "Bạn có dễ đổ mồ hôi khi hoạt động nhiều không?" },
  { id: 28, text: "Da vùng trán của bạn có tiết quá nhiều dầu không?" },
  { id: 29, text: "Bạn có cảm thấy da hoặc môi khô hay thô ráp không?" },
  { id: 30, text: "Bạn có dễ bị dị ứng không?", subText: "(Thuốc, thực phẩm, mùi, phấn hoa, thay đổi thời tiết, v.v.)" },
  { id: 31, text: "Da của bạn có dễ bị nổi mề đay hay phát ban không?" },
  { id: 32, text: "Da của bạn đã có bao giờ bị ban xuất huyết (đốm tím, vết bầm máu) do dị ứng không?" },
  { id: 33, text: "Da vùng trán của bạn có tiết quá nhiều dầu không?" },
  { id: 34, text: "Da của bạn có ửng đỏ khi gãi hoặc trầy xước không?" },
  { id: 35, text: "Môi của bạn có đỏ hơn so với người khác không?" },
  { id: 36, text: "Bạn có những mạch máu nhỏ màu đỏ, tím xuất hiện trên má của mình không?" },
  { id: 37, text: "Bạn có cảm thấy đau ở vị trí nào đó trên cơ thể không?" },
  { id: 38, text: "Bạn có gò má đỏ hoặc những cơn nóng phừng mặt không?" },
  { id: 39, text: "Bạn có cảm thấy nhờn hoặc bóng trên mặt hoặc mũi không?" },
  { id: 40, text: "Bạn có thấy sắc mặt của mình tối (không tươi, không hồng hào, sạm, nám) hoặc dễ bị đốm nâu không?" },
  { id: 41, text: "Bạn có dễ bị mụn hoặc nhọt trên cơ thể không?" },
  // Page 5
  { id: 42, text: "Mi mắt trên của bạn có bị sưng, đầy không?" },
  { id: 43, text: "Bạn có dễ bị thâm quầng hai mắt không?" },
  { id: 44, text: "Bạn có cảm thấy khô mắt không?" },
  { id: 45, text: "Môi của bạn có bị thâm không?" },
  { id: 46, text: "Bạn có cảm thấy khô miệng, họng và luôn muốn uống nước không?" },
  { id: 47, text: "Bạn có cảm giác có dị vật trong cổ họng và bạn không thể nôn hoặc nuốt không?" },
  { id: 48, text: "Bạn có cảm thấy đắng miệng hoặc có vị lạ trong miệng không?" },
  { id: 49, text: "Bạn có cảm thấy miệng dính hoặc nhớt không?" },
  { id: 50, text: "Bạn có thấy rêu lưỡi của mình trắng hoặc vàng, nhớt hoặc dày dơ không?" },
  { id: 51, text: "Bạn có thường khạc ra nhiều đờm không?" },
  { id: 52, text: "Bạn có cảm thấy khó chịu hoặc sợ khi phải ăn (uống) đồ lạnh không?" },
  { id: 53, text: "Bạn có dễ thích nghi với sự thay đổi của môi trường tự nhiên hoặc xã hội không?", subText: "Dễ thích ứng với điều kiện hoặc sự việc mới, như chuyển mùa, đổi nhà, đổi công việc,..." },
  { id: 54, text: "Bạn có dễ bị mất ngủ không?", subText: "Hơn 30 phút mới vào giấc ngủ. Hoặc sau khi tỉnh giấc vẫn còn thấy uể oải > 30 phút" },
  // Page 6
  { id: 55, text: "Bạn có dễ bị tiêu chảy (đau bụng) sau khi cảm lạnh hoặc ăn uống đồ có tính hàn không?" },
  { id: 56, text: "Bạn có cảm thấy phân của mình nhầy hoặc đi tiêu không hết phân không?" },
  { id: 57, text: "Bạn có dễ bị táo bón hay phân khô không?", subText: "Số lần đi cầu giảm, dưới 2 lần/tuần, khi đi phải rặn, lượng phân ít, khô cứng." },
  { id: 58, text: "Bụng của bạn có to ra hơn không?" },
  { id: 59, text: "Bạn có cảm thấy nóng đường tiểu hoặc nước tiểu sậm màu không?" },
  { id: 60, text: "Dành cho bạn nữ: Dịch tiết âm đạo của bạn có bị vàng không? (Nam: bộ phận sinh dục dễ bị ẩm ướt không?)" },
];